### ISSUE TITLE
Installing Mobile Detect

### ISSUE THREAD

**Issue by cstevensjr** [justonestep/processwire-mobiledetect#1]
Reference:

https://processwire.com/talk/topic/9352-fallen-at-the-first-hurdle/page-2#entry90179

Normally, ProcessWire modules are installed in one of three ways:

(1) Create a directory in the /site/modules directory with the name of your module (using CamelCase format).  Then copy the files in the directory. Go to the Modules Tab and click Refresh.
(2) Use the third-party ModulesManager by Soma to install the module.
(3) Go to Modules Tab on the Admin Menu, go to Install and click +Add New. Then you have a choice of Add Module From Directory, Add Module From URL or  ADD Module From Upload.

This module cannot be installed these ways, due to the fact that there is a mandatory requirement to run the git init and update commands on a submodule.

How any module operates or installs is totally up to the module author.  I only ask that you make it very clear and explicit that knowledge of git, to include how to run git commands is a prerequisite for the use of this module. I believe this will not be readily apparent to anyone who is not familiar or knowledgeable about Git.

I do commend you because you have already made changes to explain about the error that someone will receive if those git commands are not run.  

Finally, It would be even better if this module installed using the normal methods.

**Comment by justonestep** [comment]
I can definitely unterstand your point. Now you should be able to install the module the normal way. I removed the submodule and included the mobiledetect library via composer. Therefore the including path for the library changed but this doesn't matter for you. There is a new release version 0.0.4.

**Comment by cstevensjr** [comment]
Thanks for your prompt response to this issue.
